timeout: 3600s
steps:
  - name: 'gcr.io/$PROJECT_ID/gke-windows-builder'
    args:
    - --tag
    - 'gcr.io/$PROJECT_ID/windows-multiarch-container-demo:cloudbuild'
tags: ['cloud-builders-community']
